/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bettertown.admin;

import com.mycompany.bettertown.Feedback;
import com.mycompany.bettertown.login.DatabaseLogic;
import com.mycompany.bettertown.login.ProfileData;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author biancagrovu
 */
public class FeedbackFrame extends javax.swing.JFrame {

    /**
     * Creates new form Feedback
     */
    private ProfileData admin;
    private List<Feedback> feedbacks=new ArrayList<>();
    private int count=0;
    private double sum=0;
    private double average=0;
    private List<Feedback> allFeedbacks=new ArrayList<>();
    private List<ProfileData> users=new ArrayList<>();
    private List<ProfileData> allAdmins=new ArrayList<>();
    private int rank=1;
    public FeedbackFrame(ProfileData admin) {
        initComponents();
        this.admin=admin;
        System.out.println("In feedback: "+admin.getName());
        feedbacks=DatabaseLogic.getAllFeedback(admin);
        Number.setText(String.valueOf(feedbacks.size()));
        for(Feedback f: feedbacks)
        {
            sum+=f.getRating();
            count++;
        }
        if(count>0)
        {average=sum/count;}
        else
        {average=0;}
        Rating.setText(String.valueOf(average));
        allAdmins=DatabaseLogic.getAllAdmins();
        for(ProfileData a : allAdmins)
        {
            List<Feedback> fb=new ArrayList<>();
            fb=DatabaseLogic.getAllFeedback(a);
            System.out.println("Loaded feedbacks for admin: "+a.getName()+" "+fb.size());
            double s=0;
            int c=0;
            for(Feedback f: fb)
                {
                    s+=f.getRating();
                    c++;
                }
            double avg;
            if(c>0)
            {avg=s/c;}
            else
            {avg=0;}
            System.out.println(a.getName()+" "+avg+" "+admin.getName()+" "+average);
            if(avg>average)
                rank++;
            
        }
        Rank.setText(String.valueOf(rank));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Rating = new javax.swing.JLabel();
        Number = new javax.swing.JLabel();
        Rank = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        jLabel1.setText("Feedback");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel2.setText("Rating");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel3.setText("Number of issues solved");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel4.setText("Rank");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        Rating.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        Rating.setText("jLabel5");
        jPanel2.add(Rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        Number.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        Number.setText("jLabel6");
        jPanel2.add(Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        Rank.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        Rank.setText("jLabel7");
        jPanel2.add(Rank, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255), 2));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 390, 190));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedbackFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedbackFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedbackFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedbackFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FeedbackFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Number;
    private javax.swing.JLabel Rank;
    private javax.swing.JLabel Rating;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
