/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bettertown.admin;

import com.mycompany.bettertown.IssueData;
import com.mycompany.bettertown.SolvedIssues;
import com.mycompany.bettertown.login.DatabaseLogic;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author biancagrovu
 */
public class Statistics extends javax.swing.JFrame {

    /**
     * Creates new form Statistics
     */
    private List<IssueData> issues=new ArrayList<>();
    private List<SolvedIssues> solvedIssues=new ArrayList<>();
    private int solved=0;
    private int progress=0;
    private int unresolved=0;
    private int count=0;
    private long totalSeconds=0;
    public Statistics() {
        initComponents();
        issues=DatabaseLogic.getAllIssues();
        solvedIssues=DatabaseLogic.getAllSolvedIssues();
        Number.setText(String.valueOf(issues.size()));
        for(IssueData i : issues)
        {
            if(i.getStatus().equals("Resolved"))
            {
                solved++;
            }
            if(i.getStatus().equals("In Progress"))
            {
                progress++;
            }
            if(i.getStatus().equals("Not resolved"))
            {
                unresolved++;
            }
        }
        Unresolved.setText(String.valueOf(unresolved));
        Progress.setText(String.valueOf(progress));
        Solved.setText(String.valueOf(solved));
        for(SolvedIssues s: solvedIssues)
        {
            for(IssueData i : issues)
            {
                if(i.getId()==s.getIssueId())
                {System.out.println(i.getTitle());
                 Duration d=Duration.between(i.getDate(), s.getDate());
                 totalSeconds+=d.getSeconds();
                 count++;
                 //break;
                }
            }
        }
        if(count > 0)
        {
            long mediaSecunde = totalSeconds / count;

            long zile = mediaSecunde / (24 * 60 * 60);
            long ore = (mediaSecunde % (24 * 60 * 60)) / 3600;
            long minute = (mediaSecunde % 3600) / 60;

            String average = zile + " zile, " + ore + " ore și " + minute + " minute";
            Average.setText(average);
        }
        else
        {
            Average.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Number = new javax.swing.JLabel();
        Unresolved = new javax.swing.JLabel();
        Progress = new javax.swing.JLabel();
        Solved = new javax.swing.JLabel();
        Average = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel1.setText("Number of issues:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel2.setText("Unresolved issues:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel3.setText("In progress issues:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel4.setText("Solved issues:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel5.setText("Statistics");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel6.setText("Average solving time:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        Number.setText("jLabel7");
        jPanel1.add(Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        Unresolved.setText("jLabel8");
        jPanel1.add(Unresolved, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        Progress.setText("jLabel9");
        jPanel1.add(Progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        Solved.setText("jLabel10");
        jPanel1.add(Solved, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        Average.setText("jLabel11");
        jPanel1.add(Average, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255), 2));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 440, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Average;
    private javax.swing.JLabel Number;
    private javax.swing.JLabel Progress;
    private javax.swing.JLabel Solved;
    private javax.swing.JLabel Unresolved;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
